spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineplatform?characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm
